name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Update Homebrew Formula
        run: |
          # Extract version from tag
          VERSION=${GITHUB_REF#refs/tags/v}
          
          # Create temporary directory
          mkdir -p tmp/formula
          
          # Copy formula template
          cp homebrew/mcpvault.rb tmp/formula/
          
          # Get checksum for macOS binary
          DARWIN_AMD64_CHECKSUM=$(sha256sum dist/mcpvault_${VERSION}_darwin_amd64.tar.gz | cut -d ' ' -f 1)
          
          # Update formula
          sed -i "s|/v[0-9.]*_darwin_amd64|/v${VERSION}_darwin_amd64|g" tmp/formula/mcpvault.rb
          sed -i "s|PLACEHOLDER_FOR_CHECKSUM|${DARWIN_AMD64_CHECKSUM}|g" tmp/formula/mcpvault.rb
          
          echo "Updated Homebrew formula with version ${VERSION} and checksum ${DARWIN_AMD64_CHECKSUM}" 